import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TmaSDKLoader } from "./component/TmaSDKLoader";
import { ThemeProvider } from "@mui/material/styles";
import theme from "./theme/theme";
import StoreProvider from "./StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
      <html lang="en">
        <body className={inter.className}>
          <StoreProvider>
            <ThemeProvider theme={theme}>
              <TmaSDKLoader>{children}</TmaSDKLoader>
              {/* {children} */}
            </ThemeProvider>
          </StoreProvider>
        </body>
      </html>
  );
}
