export const NOTIFICATION_TYPES = {
  CREATE_SUB_LIXIES: 1,
  WITHDRAW_SUB_LIXIES: 2,
  EXPORT_SUB_LIXIES: 3,
  NEW_POST: 14,
  PAGE_MESSAGE_REQUEST: 15,
  PAGE_MESSAGE_ACCEPT: 16,
  PAGE_MESSAGE_DENIED: 17
};
